defaults:
  - agents: beso_block_push 
  - workspaces: block_pushing_manager

log_dir: logs/block_pushing/
plot_dir: plots/block_pushing/
plot_name: ${now:%Y-%m-%d}.png
data_path: /path/to/beso/environments/data/cbet_datasets/multimodal_push_fixed_target

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/sweeps/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

group: group_name

wandb:
  entity: add_wandb_acc_name
  project: beso_experiments

# general params
device: 'cuda'
seed: 6
scale_data: True
future_seq_length: 1
window_size: 5
mask_targets: False
reduce_obs_dim: true

goal_conditioning: True
goal_conditional: 'future'
action_dim: 2
input_dim: 18
obs_dim: 10
goal_dim: 4

# policy model params
hidden_dim: 240 # for transformer, must be a multiple of n_heads (6 in diffusion_gpt)
use_spectral_norm: false
num_hidden_layers: 4
train_method: 'steps'
max_train_steps: 60000
max_epochs: 100
eval_every_n_steps: 4000

# define evaluation types 
evaluate_multigoal: True
evaluate_sequential: True

obs_modalities: ['observation']
goal_modalities: ['goal_observation']
target_modality: 'action'

# BESO hyperparameters
attn_pdrop: 0.05
resid_pdrop: 0.05
n_heads: 12
t_dim: 16 # onlu used for score mlps only
use_ema: True
decay: 0.999 
update_ema_every_n_steps: 1
sigma_data: 0.5 
cond_mask_prob: 0.1
cond_lambda: 2 # only required for inference of CFG-BESO
n_timesteps: 3 # number of diffusion steps during inference
